export default function getThumbnailList() {
	return (
		[
			{
				id: 1,
				src: '/thumbnails/校园风光-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 2,
				src: '/thumbnails/校园风光-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 3,
				src: '/thumbnails/校园风光-3_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 4,
				src: '/thumbnails/校园风光-4_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 5,
				src: '/thumbnails/校园风光-5_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 6,
				src: '/thumbnails/校园风光-6_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 7,
				src: '/thumbnails/校园风光-7_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 8,
				src: '/thumbnails/校园风光-8_tn.jpg',
				width: 100,
				height: 75,
			},	
			{
				id: 9,
				src: '/thumbnails/校园风光-9_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 10,
				src: '/thumbnails/校园风光-10_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 11,
				src: '/thumbnails/校园风光-11_tn.jpg',
				width: 100,
				height: 75,
			},	
			{
				id: 12,
				src: '/thumbnails/校园风光-12_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 13,
				src: '/thumbnails/校园风光-13_tn.jpg',
				width: 100,
				height: 75,
			},	
			{
				id: 14,
				src: '/thumbnails/校园风光-14_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 15,
				src: '/thumbnails/校园风光-15_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 16,
				src: '/thumbnails/校园风光-16_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 17,
				src: '/thumbnails/校园风光-17_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 18,
				src: '/thumbnails/校园风光-18_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 19,
				src: '/thumbnails/班级同学-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 20,
				src: '/thumbnails/班级同学-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 21,
				src: '/thumbnails/班级同学-3_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 22,
				src: '/thumbnails/班级同学-4_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 23,
				src: '/thumbnails/班级同学-5_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 24,
				src: '/thumbnails/班级同学-6_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 25,
				src: '/thumbnails/班级同学-7_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 26,
				src: '/thumbnails/班级同学-8_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 27,
				src: '/thumbnails/班级同学-9_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 28,
				src: '/thumbnails/班级同学-10_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 29,
				src: '/thumbnails/班级同学-11_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 30,
				src: '/thumbnails/班级同学-12_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 31,
				src: '/thumbnails/班级同学-13_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 32,
				src: '/thumbnails/班级同学-14_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 33,
				src: '/thumbnails/班级同学-15_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 34,
				src: '/thumbnails/班级同学-16_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 35,
				src: '/thumbnails/行A405-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 36,
				src: '/thumbnails/行A405-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 37,
				src: '/thumbnails/行A405-3_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 38,
				src: '/thumbnails/行A405-4_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 39,
				src: '/thumbnails/行A405-5_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 40,
				src: '/thumbnails/行A405-6_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 41,
				src: '/thumbnails/行A405-7_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 42,
				src: '/thumbnails/行A405-8_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 43,
				src: '/thumbnails/宿舍-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 44,
				src: '/thumbnails/宿舍-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 45,
				src: '/thumbnails/宿舍-3_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 46,
				src: '/thumbnails/宿舍-4_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 47,
				src: '/thumbnails/204c阳台风景1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 48,
				src: '/thumbnails/204c阳台风景2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 49,
				src: '/thumbnails/图书馆-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 50,
				src: '/thumbnails/图书馆-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 51,
				src: '/thumbnails/图书馆-3_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 52,
				src: '/thumbnails/图书馆-4_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 53,
				src: '/thumbnails/小猫咪-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 54,
				src: '/thumbnails/小猫咪-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 55,
				src: '/thumbnails/信工院_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 56,
				src: '/thumbnails/下雨天-1_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 57,
				src: '/thumbnails/下雨天-2_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 58,
				src: '/thumbnails/下雨天-3_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 59,
				src: '/thumbnails/下雨天-4_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 60,
				src: '/thumbnails/下雨天-5_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 61,
				src: '/thumbnails/下雨天-6_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 62,
				src: '/thumbnails/下雨天-7_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 63,
				src: '/thumbnails/下雨天-8_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 64,
				src: '/thumbnails/下雨天-9_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 65,
				src: '/thumbnails/下雨天-10_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 66,
				src: '/thumbnails/我们毕业啦_tn.jpg',
				width: 100,
				height: 75,
			},
			{
				id: 67,
				src: '/thumbnails/19计科卓工_tn.jpg',
				width: 100,
				height: 75,
			}
		]		
	)
}