-- Apply this migration before deploying the server-secret comment API.
--
-- Runtime configuration (never bake these into the image):
--   SUPABASE_URL
--   SUPABASE_SECRET_KEY (or legacy SUPABASE_SERVICE_ROLE_KEY)
--   CLOUDFLARE_TURNSTILE_SECRET_KEY
--   COMMENT_EMAIL_VERIFICATION_SECRET (at least 32 random characters)
--   COMMENT_API_ENABLED=true
--   COMMENT_CLIENT_IP_HEADER (the one header overwritten by your proxy)
--   EMAIL_* and MASTER_EMAIL, when email delivery is enabled
--
-- The public site origin remains NEXT_PUBLIC_SITE_URL. Set the Turnstile widget
-- action to `comment`; override the server expectation only with
-- CLOUDFLARE_TURNSTILE_EXPECTED_ACTION when both sides are changed together.

begin;

-- This repository previously assumed a manually-created table. Define a safe
-- baseline as well as remaining compatible with existing deployments.
create table if not exists public.comments (
	id bigint generated by default as identity primary key,
	username text not null,
	email text not null,
	website text,
	content text not null,
	created_at timestamptz not null default now(),
	url text not null,
	parent_comment_id bigint,
	email_verified_at timestamptz,
	constraint comments_username_bounded
		check (char_length(username) between 1 and 64),
	constraint comments_email_bounded
		check (char_length(email) between 3 and 254),
	constraint comments_website_bounded
		check (website is null or char_length(website) <= 200),
	constraint comments_content_bounded
		check (char_length(content) between 1 and 5000),
	constraint comments_url_bounded
		check (char_length(url) between 1 and 2048),
	constraint comments_created_at_present check (created_at is not null),
	constraint comments_parent_comment_foreign_key
		foreign key (parent_comment_id) references public.comments(id)
		on delete set null
);

alter table public.comments
	add column if not exists email_verified_at timestamptz;

-- Fail clearly if a hand-created legacy table is incompatible instead of
-- silently completing a migration that the runtime cannot use safely.
do $migration$
declare
	compatible_columns integer;
	incompatible_required_columns text;
	id_identity text;
	comment_id_sequence text;
	maximum_id bigint;
	sequence_last_value bigint;
begin
	select count(*) into compatible_columns
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'comments'
		and (
			(column_name = 'id' and data_type in ('bigint', 'integer'))
			or (column_name = 'username'
				and (data_type = 'text' or (
					data_type = 'character varying'
					and (character_maximum_length is null or character_maximum_length >= 64)
				)))
			or (column_name = 'email'
				and (data_type = 'text' or (
					data_type = 'character varying'
					and (character_maximum_length is null or character_maximum_length >= 254)
				)))
			or (column_name = 'website'
				and (data_type = 'text' or (
					data_type = 'character varying'
					and (character_maximum_length is null or character_maximum_length >= 200)
				)))
			or (column_name = 'content'
				and (data_type = 'text' or (
					data_type = 'character varying'
					and (character_maximum_length is null or character_maximum_length >= 5000)
				)))
			or (column_name = 'url'
				and (data_type = 'text' or (
					data_type = 'character varying'
					and (character_maximum_length is null or character_maximum_length >= 2048)
				)))
			or (column_name = 'created_at'
				and data_type = 'timestamp with time zone')
			or (column_name = 'parent_comment_id'
				and data_type in ('bigint', 'integer'))
			or (column_name = 'email_verified_at'
				and data_type = 'timestamp with time zone')
		)
		and is_generated = 'NEVER';

	if compatible_columns <> 9 then
		raise exception
			'public.comments has missing or incompatible columns; reconcile it with this migration before deployment';
	end if;

	select string_agg(column_name, ', ' order by ordinal_position)
		into incompatible_required_columns
	from information_schema.columns
	where table_schema = 'public'
		and table_name = 'comments'
		and column_name not in (
			'id', 'username', 'email', 'website', 'content', 'created_at',
			'url', 'parent_comment_id', 'email_verified_at'
		)
		and is_nullable = 'NO'
		and column_default is null
		and is_identity <> 'YES'
		and is_generated = 'NEVER';

	if incompatible_required_columns is not null then
		raise exception
			'public.comments has required columns without defaults that the API cannot insert: %',
			incompatible_required_columns;
	end if;

	-- Root comments and unverified/local users require these columns to remain
	-- nullable. Dropping NOT NULL does not rewrite or discard legacy data.
	alter table public.comments
		alter column website drop not null,
		alter column parent_comment_id drop not null,
		alter column email_verified_at drop not null;

	if exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass and contype = 'p'
	) and not exists (
		select 1
		from pg_constraint constraint_definition
		join lateral unnest(constraint_definition.conkey) as key_column(attnum) on true
		join pg_attribute attribute_definition
			on attribute_definition.attrelid = constraint_definition.conrelid
			and attribute_definition.attnum = key_column.attnum
		where constraint_definition.conrelid = 'public.comments'::regclass
			and constraint_definition.contype = 'p'
		group by constraint_definition.oid
		having count(*) = 1 and bool_and(attribute_definition.attname = 'id')
	) then
		raise exception 'public.comments primary key must be the id column';
	end if;

	if not exists (
		select 1
		from pg_constraint constraint_definition
		join lateral unnest(constraint_definition.conkey) as key_column(attnum) on true
		join pg_attribute attribute_definition
			on attribute_definition.attrelid = constraint_definition.conrelid
			and attribute_definition.attnum = key_column.attnum
		where constraint_definition.conrelid = 'public.comments'::regclass
			and constraint_definition.contype = 'p'
		group by constraint_definition.oid
		having count(*) = 1 and bool_and(attribute_definition.attname = 'id')
	) then
		alter table public.comments
			add constraint comments_id_primary_key primary key (id);
	end if;

	select is_identity
		into id_identity
	from information_schema.columns
	where table_schema = 'public' and table_name = 'comments' and column_name = 'id';

	select pg_get_serial_sequence('public.comments', 'id')
		into comment_id_sequence;
	if id_identity <> 'YES' and comment_id_sequence is null then
		alter table public.comments alter column id drop default;
		alter table public.comments
			alter column id add generated by default as identity;
		select pg_get_serial_sequence('public.comments', 'id')
			into comment_id_sequence;
	elsif id_identity <> 'YES' then
		-- An owned sequence is not sufficient: explicitly make it the default so
		-- a legacy DEFAULT 0 (or another unrelated expression) cannot survive.
		execute format(
			'alter table public.comments alter column id set default nextval(%L::regclass)',
			comment_id_sequence
		);
	end if;

	if comment_id_sequence is null then
		raise exception
			'public.comments.id must use an identity or sequence-backed default';
	end if;

	select coalesce(max(id), 0) into maximum_id from public.comments;
	execute format('select last_value from %s', comment_id_sequence::regclass)
		into sequence_last_value;
	if maximum_id >= sequence_last_value then
		perform setval(comment_id_sequence::regclass, maximum_id, true);
	end if;

	alter table public.comments alter column created_at set default now();

	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_parent_comment_foreign_key'
	) then
		alter table public.comments
			add constraint comments_parent_comment_foreign_key
			foreign key (parent_comment_id) references public.comments(id)
			on delete set null not valid;
	end if;
end
$migration$;

-- `create table if not exists` does not retrofit constraints onto an existing
-- installation. Add named NOT VALID checks so new writes are protected without
-- making deployment fail on legacy rows that may need manual cleanup first.
do $migration$
begin
	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_username_bounded'
	) then
		alter table public.comments
			add constraint comments_username_bounded
			check (username is not null and char_length(username) between 1 and 64)
			not valid;
	end if;

	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_email_bounded'
	) then
		alter table public.comments
			add constraint comments_email_bounded
			check (email is not null and char_length(email) between 3 and 254)
			not valid;
	end if;

	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_website_bounded'
	) then
		alter table public.comments
			add constraint comments_website_bounded
			check (website is null or char_length(website) <= 200)
			not valid;
	end if;

	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_content_bounded'
	) then
		alter table public.comments
			add constraint comments_content_bounded
			check (content is not null and char_length(content) between 1 and 5000)
			not valid;
	end if;

	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_url_bounded'
	) then
		alter table public.comments
			add constraint comments_url_bounded
			check (url is not null and char_length(url) between 1 and 2048)
			not valid;
	end if;

	if not exists (
		select 1 from pg_constraint
		where conrelid = 'public.comments'::regclass
			and conname = 'comments_created_at_present'
	) then
		alter table public.comments
			add constraint comments_created_at_present
			check (created_at is not null)
			not valid;
	end if;
end
$migration$;

-- Before validating the checks on an upgraded database, inspect and quarantine
-- or repair legacy rows that violate them, then run:
--   alter table public.comments validate constraint comments_username_bounded;
--   alter table public.comments validate constraint comments_email_bounded;
--   alter table public.comments validate constraint comments_website_bounded;
--   alter table public.comments validate constraint comments_content_bounded;
--   alter table public.comments validate constraint comments_url_bounded;
--   alter table public.comments validate constraint comments_created_at_present;
--   alter table public.comments validate constraint comments_parent_comment_foreign_key;

alter table public.comments enable row level security;

create index if not exists comments_thread_created_id_idx
	on public.comments (url, created_at desc, id desc);

-- All comment reads and writes now pass through the Next.js server route. RLS
-- policies alone are not enough if a table/view grant later becomes permissive,
-- so remove the underlying PostgREST privileges from every browser role.
revoke all privileges on table public.comments from public, anon, authenticated;
grant select, insert, update on table public.comments to service_role;

-- Identity/serial defaults use a sequence whose name can vary in an existing
-- installation, so discover it rather than assuming `comments_id_seq`.
do $migration$
declare
	comment_id_sequence text;
begin
	select pg_get_serial_sequence('public.comments', 'id')
		into comment_id_sequence;
	if comment_id_sequence is not null then
		execute format(
			'revoke all privileges on sequence %s from public, anon, authenticated',
			comment_id_sequence
		);
		execute format(
			'grant usage, select on sequence %s to service_role',
			comment_id_sequence
		);
	end if;
end
$migration$;

-- Older deployments exposed notification addresses through this view. Keep the
-- migration idempotent for installations where the view was already removed.
do $migration$
begin
	if to_regclass('public.comment_emails') is not null then
		execute
			'revoke all privileges on table public.comment_emails from public, anon, authenticated';
	end if;
end
$migration$;

commit;
